In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from os import listdir
from PIL import Image
from tensorflow.keras.utils import to_categorical

In [46]:
# Encoding and Decoding the labels example
testingCategories = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 3, 4, 1, 3, 1])
categories = to_categorical(testingCategories)
print(categories)

backdecode = tf.argmax(categories, axis=1)
print(backdecode)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10  1  3  4  1  3  1], shape=(17,), dtype=int64)


In [ ]:
# Files Testing
mainDirectory = "images"
label_names = sorted(fn for fn in listdir(mainDirectory))
label_numcat = [i for i in range(len(label_names))]
for i in label_numcat:
    print(i, label_names[i])

# Print the arrays to use on other ipynb
print(label_names)
print(label_numcat)

In [ ]:
# IMAGE PREPARATION

In [2]:
def processImage(path):
    raw = Image.open(path)
    if raw.mode == "RGBA":
        raw = raw.convert("RGB")
    raw = raw.resize((100, 100))
    return np.array(raw)

In [5]:
# Creating an ndarray for the images and labels
dataImg = np.zeros((0, 100, 100, 3), dtype=np.uint8)
dataCat = []
# Read all the images
for index, i in enumerate(label_names):
    currentDirectory = "%s/%s" % (mainDirectory, i)
    for j in listdir(currentDirectory):
        img = processImage("%s/%s" % (currentDirectory, j))
        dataImg = np.concatenate((dataImg, [img]))
        dataCat.append(index)

In [8]:
# Change labels into categories and save the ndarrays into files
dataCat = to_categorical(dataCat)
np.save("label_data.npy", dataCat)
np.save("image_data.npy", dataImg)

In [57]:
def decode(coded):
    return np.argmax(coded, axis=1)

In [ ]:
# Displaying the images
label_decoded = [label_names[i] for i in decode(dataCat)]
for i in range(11730):
    plt.xticks([])
    plt.yticks([])
    plt.xlabel(label_decoded[i])
    plt.imshow(dataImg[i])
    plt.show()